# Gitlab ci/cd file configuration 

stages:
    - build-image
    - compiling
    - testing
    - cleanup

build-image:
    image: docker 
    services: docker:dind
    script:
        - echo $CI_REGISTRY_PASSWORD | docker login -u  $CI_REGISTRY_USER $CI_REGISTRY gitlab.ensimag.fr:5050 --password-stdin
        - docker build -t gitlab.ensimag.fr:5050/gl2022/g9/gl49 .
        - docker push gitlab.ensimag.fr:5050/gl2022/g9/gl49

compile_job:
    stage: compiling
    image: gitlab.ensimag.fr:5050/gl2022/g9/gl49
    script:
        - echo "Trying to compile src files..."
        - mvn compile

test_compile_job:
    stage: compiling
    script:
        - echo "Trying to compile test files..."

script_execution_job:
    dependencies:
        - compile_job
        - test_compile_job
    stage: testing
    script:
        - echo "A ce niveau là, on devrait réussir à lancer les tests"
        
no_regression_job:
    dependencies:
        - compile_job
        - test_compile_job
    stage: testing
    script:
        - echo "A ce niveau là, on devrait pouvoir lancer les tests de non-régression"



cleanup_job:
    stage: cleanup
    script:
        - mvn clean
    when: on_failure
